const duplicatedPanel = [
  {
    xSteps: 3,
    ySteps: 3,
    columns: [
      { title: "Month" },
      { title: "IDs" },
      { title: "Resp Name" },
      { title: "Telephone" },
      { title: "Interviewer Id" },
      { title: "Region" },
    ],
    data: [
      [
        { value: "Apr" },
        { value: 34544 },
        { value: "Abraham Mends" },
        { value: "23355643456" },
        { value: "344354" },
        { value: "Central" },
      ],
      [
        { value: "Mar" },
        { value: 23434 },
        { value: "Yaw Adade" },
        { value: "23357843456" },
        { value: "344354" },
        { value: "Western" },
      ],
      [
        { value: "Apr" },
        { value: 34544 },
        { value: "Abraham Mends" },
        { value: "23355643456" },
        { value: "344354" },
        { value: "Central" },
      ],
      [
        { value: "Mar" },
        { value: 23434 },
        { value: "Yaw Adade" },
        { value: "23357843456" },
        { value: "344354" },
        { value: "Western" },
      ],
      [
        { value: "Apr" },
        { value: 34544 },
        { value: "Abraham Mends" },
        { value: "23355643456" },
        { value: "344354" },
        { value: "Central" },
      ],
      [
        { value: "Mar" },
        { value: 23434 },
        { value: "Yaw Adade" },
        { value: "23357843456" },
        { value: "344354" },
        { value: "Western" },
      ],
    ],
  },
  // {
  //   xSteps: 1, // Will start putting cell with 1 empty cell on left most
  //   ySteps: 5, //will put space of 5 rows,
  //   columns: ["Name", "Department"],
  //   data: [
  //     ["Johnson", "Finance"],
  //     ["Monika", "IT"],
  //     ["Konstantina", "IT Billing"],
  //     ["John", "HR"],
  //     ["Josef", "Testing"],
  //   ],
  // },
];

const deletIds = [
  {
    xSteps: 3,
    ySteps: 3,
    columns: [
      { title: "Count" },
      { title: "Respondent_serial" },
      { title: "Respondent Id" },
      { title: "Interviewer_Id" },
      { title: "Reasons for cancellation" },
    ],
    data: [
      [
        { value: 1 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 2 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 3 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 4 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 5 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 6 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 6 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 7 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 8 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 9 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 10 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 11 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 12 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 13 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 14 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 15 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 16 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 17 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 18 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 19 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
      [
        { value: 20 },
        { value: "45hjdj43ljdkhdjoie" },
        { value: 32434 },
        { value: 3434 },
        { value: "Low LOI" },
      ],
    ],
  },
];

const supervisorAcc = [
  {
    xSteps: 2,
    ySteps: 2,
    columns: [
      { title: "Count" },
      { title: "Start time" },
      { title: "Completion Time" },
      { title: "Date of Interview" },
      { title: "QC/supervisor name" },
      { title: "Region" },
      { title: "Count" },
      { title: "Start time" },
      { title: "Completion Time" },
      { title: "Date of Interview" },
      { title: "QC/supervisor name" },
      { title: "Region" },
      { title: "Count" },
      { title: "Start time" },
      { title: "Completion Time" },
      { title: "Date of Interview" },
      { title: "QC/supervisor name" },
      { title: "Region" },
    ],
    data: [
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
      [
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
        { value: 1 },
        { value: "9:56" },
        { value: "10:06" },
        { value: "12/06/21" },
        { value: "Supervisor name" },
        { value: "BA" },
      ],
    ],
  },
];

const infieldAcc = [
  {
    xSteps: 2,
    ySteps: 2,
    columns: [
      { title: "Region" },
      { title: "Target" },
      { title: "Achieved" },
      { title: "Supervisor infield" },
      { title: "QC" },
      { title: "Total % of Supervisor" },
      { title: "Total of QM infield acc" },
    ],
    data: [
      [
        { value: "Accra" },
        { value: 343 },
        { value: 234 },
        { value: 23 },
        { value: 45 },
        { value: 12 },
        { value: 23 },
      ],
      [
        { value: "Cape Coast" },
        { value: 343 },
        { value: 234 },
        { value: 23 },
        { value: 45 },
        { value: 12 },
        { value: 23 },
      ],
      [
        { value: "HO" },
        { value: 343 },
        { value: 234 },
        { value: 23 },
        { value: 45 },
        { value: 12 },
        { value: 23 },
      ],
      [
        { value: "Koforidua" },
        { value: 343 },
        { value: 234 },
        { value: 23 },
        { value: 45 },
        { value: 12 },
        { value: 23 },
      ],
      [
        { value: "Kumasi" },
        { value: 343 },
        { value: 234 },
        { value: 23 },
        { value: 45 },
        { value: 12 },
        { value: 23 },
      ],
      [
        { value: "Sunyani" },
        { value: 343 },
        { value: 234 },
        { value: 23 },
        { value: 45 },
        { value: 12 },
        { value: 23 },
      ],
    ],
  },
];

const summaryOfCancelled = [
  {
    xSteps: 2,
    ySteps: 2,
    columns: [{ title: "Reasons for cancellation", width: { wch: 20 } }],
    data: [],
  },
  {
    columns: [
      { title: "Interviewer per Region", width: { wch: 5 } },
      { title: "LOI issue", width: { wch: 5 } },
      { title: "Test Interviews", width: { wch: 5 } },
      { title: "Quota Issues", width: { wch: 5 } },
      { title: "Duplicate Interviews", width: { wch: 5 } },
      { title: "Quality Issues", width: { wch: 5 } },
      { title: "Grand Total", width: { wch: 5 } },
    ],
    data: [
      [
        { value: "Accra" },
        { value: 2 },
        { value: 4 },
        { value: 1 },
        { value: 0 },
        { value: 0 },
        { value: 7 },
      ],
      [
        { value: 13545 },
        { value: 2 },
        { value: 4 },
        { value: 1 },
        { value: 0 },
        { value: 0 },
        { value: 7 },
      ],
      [
        { value: 54564 },
        { value: 2 },
        { value: 4 },
        { value: 1 },
        { value: 0 },
        { value: 0 },
        { value: 7 },
      ],
      [
        { value: 234454 },
        { value: 2 },
        { value: 4 },
        { value: 1 },
        { value: 0 },
        { value: 0 },
        { value: 7 },
      ],
      [
        { value: 34565 },
        { value: 2 },
        { value: 4 },
        { value: 1 },
        { value: 0 },
        { value: 0 },
        { value: 7 },
      ],
      [
        { value: 74342 },
        { value: 2 },
        { value: 4 },
        { value: 1 },
        { value: 0 },
        { value: 0 },
        { value: 7 },
      ],
      [
        { value: 234543 },
        { value: 2 },
        { value: 4 },
        { value: 1 },
        { value: 0 },
        { value: 0 },
        { value: 7 },
      ],
    ],
  },
];

const qcSummary = [
  {
    xSteps: 2,
    ySteps: 2,
    columns: [],
    data: [
      [{ value: "Project sample" }, { value: 1456 }],
      [{ value: "Field Achieved" }, { value: 1356 }],
      [{ value: "Percentage Field Achieved" }, { value: 110 }],
      [{ value: "Total QC required" }, { value: 24 }],
      [{ value: "QC approved" }, { value: 45 }],
      [{ value: "% QC approved" }, { value: 13 }],
      [{ value: "Rejecting" }, { value: 1456 }],
      [{ value: "% Cancelled interviews" }, { value: 40 }],
    ],
  },
  {
    xSteps: 2,
    ySteps: 2,
    columns: [
      { title: "" },
      { title: "Approved" },
      { title: "Canceled" },
      { title: "LOI issue" },
      { title: "Test Interviews" },
      { title: "Quota Issues" },
      { title: "Duplicate Interviews" },
      { title: "Quality Issues" },
    ],
    data: [
      [
        { value: "QC Achievement" },
        { value: 1233 },
        { value: 112 },
        { value: 112 },
        { value: 112 },
        { value: 112 },
        { value: 112 },
        { value: 112 },
      ],
      [
        { value: "Grand Total" },
        { value: 1233 },
        { value: 112 },
        { value: 112 },
        { value: 112 },
        { value: 112 },
        { value: 112 },
        { value: 112 },
      ],
    ],
  },
];

export const allData = {
  qc_summary: qcSummary,
  summary_of_cancelled: summaryOfCancelled,
  infield_acc: infieldAcc,
  qc_acc: supervisorAcc,
  supervisor_acc: supervisorAcc,
  deleted_ids: deletIds,
  duplication_of_panel: duplicatedPanel,
};
